site_name: Magoh Extract Exps Docs

theme:
  name: "material"

plugins:
  - mkdocstrings:
      handlers:
        python:
          options:
            show_root_full_path: true
            show_root_heading: true

nav:
- Magoh Extract Exps Docs: index.md
- tutorials.md
- How-To Guides: how-to-guides.md
- Reference:
  - Overview: reference.md
  - Dataset loading:
      - refs/dataset.md 
      - refs/thesauri.md

- explanation.md
