site_name: Magoh Extract Exps Docs
site_url: https://localhost:8000/docs

theme:
  name: material
  highlightjs: true
  hljs_language:
    - python
  features:
    - navigation.indexes
    - navigation.expand
    - navigation.indexes
    - navigation.sections
    - navigation.tabs

nav:
  - Magoh Extract Exps Docs: index.md
  - install.md
  - How-To Guides: how-to-guides.md
  - explanation.md
  - Reference: $api/archaeo_super_prompt.***
  - about.md

plugins:
  - mkapi:
      config: config.py
